apiVersion: storage.gcp.upbound.io/v1beta1
kind: Bucket
metadata:
  annotations:
    meta.upbound.io/example-id: storage/v1beta1/notification
  labels:
    demo.yocoe.upbound.io/yocoe-name: yocoe-bucket
  name: yocoe-bucket-demo
spec:
  forProvider:
    location: US
  providerConfigRef:
    name: gcp-provider-conf
